#!/bin/bash
clear
echo -e "\E[44;1;37m     INSTALACION DE AUTO BOT +APK BY GATESCCN     \E[0m"
echo -e "\nINSTALANDO ESPERE...."
apt update -y > /dev/null 2>&1 && apt install unzip at jq curl -y > /dev/null 2>&1
mkdir $HOME/BOT
cd $HOME/BOT && wget https://github.com/gatesccn01/botssh2022v1/blob/main/botventas.zip?raw=true
unzip botventas.zip > /dev/null 2>&1 && rm botventas.zip > /dev/null 2>&1
chmod +x $(ls)
mv botventas /bin/botventas
clear && echo -e "INSTALADO COM SUCESSO !\nPARA ATIVAR EXECULTE O COMANDO botteste"
cd $HOME && rm inst-botventas > /dev/null 2>&1
